INSERT INTO country VALUES ('AALAND_ISLANDS', 'Aaland Islands');
INSERT INTO country VALUES ('AFGHANISTAN', 'Afghanistan');
INSERT INTO country VALUES ('ALBANIA', 'Albania');
INSERT INTO country VALUES ('ALGERIA', 'Algeria');
INSERT INTO country VALUES ('AMERICAN_SAMOA', 'American Samoa');
INSERT INTO country VALUES ('ANDORRA', 'Andorra');
INSERT INTO country VALUES ('ANGOLA', 'Angola');
INSERT INTO country VALUES ('ANGUILLA', 'Anguilla');
INSERT INTO country VALUES ('ANTARCTICA', 'Antarctica');
INSERT INTO country VALUES ('ANTIGUA_AND_BARBUDA', 'Antigua and Barbuda');
INSERT INTO country VALUES ('ARGENTINA', 'Argentina');
INSERT INTO country VALUES ('ARMENIA', 'Armenia');
INSERT INTO country VALUES ('ARUBA', 'Aruba');
INSERT INTO country VALUES ('AUSTRALIA', 'Australia');
INSERT INTO country VALUES ('AUSTRIA', 'Austria');
INSERT INTO country VALUES ('AZERBAIJAN', 'Azerbaijan');
INSERT INTO country VALUES ('BAHAMAS', 'Bahamas');
INSERT INTO country VALUES ('BAHRAIN', 'Bahrain');
INSERT INTO country VALUES ('BANGLADESH', 'Bangladesh');
INSERT INTO country VALUES ('BARBADOS', 'Barbados');
INSERT INTO country VALUES ('BELARUS', 'Belarus');
INSERT INTO country VALUES ('BELGIUM', 'Belgium');
INSERT INTO country VALUES ('BELIZE', 'Belize');
INSERT INTO country VALUES ('BENIN', 'Benin');
INSERT INTO country VALUES ('BERMUDA', 'Bermuda');
INSERT INTO country VALUES ('BHUTAN', 'Bhutan');
INSERT INTO country VALUES ('BOLIVIA', 'Boliva');
INSERT INTO country VALUES ('BOSNIA_AND_HERZEGOWINA', 'Bosnia and Herzegowina');
INSERT INTO country VALUES ('BOTSWANA', 'Botswana');
INSERT INTO country VALUES ('BOUVET_ISLAND', 'Bouvet Island');
INSERT INTO country VALUES ('BRAZIL', 'Brazil');
INSERT INTO country VALUES ('BRITISH_INDIAN_OCEAN_TERRITORY', 'British Indian Ocean Territory');
INSERT INTO country VALUES ('BRUNEI_DARUSSALAM', 'Brunei Darussalam');
INSERT INTO country VALUES ('BULGARIA', 'Bulgaria');
INSERT INTO country VALUES ('BURKINA_FASO', 'Burkina Faso');
INSERT INTO country VALUES ('BURUNDI', 'Burundi');
INSERT INTO country VALUES ('CAMBODIA', 'Cambodia');
INSERT INTO country VALUES ('CAMEROON', 'Cameroon');
INSERT INTO country VALUES ('CANADA', 'Canada');
INSERT INTO country VALUES ('CAPE_VERDE', 'Cape Verde');
INSERT INTO country VALUES ('CAYMAN_ISLANDS', 'Cayman Islands');
INSERT INTO country VALUES ('CENTRAL_AFRICAN_REPUBLIC', 'Central African Republic');
INSERT INTO country VALUES ('CHAD', 'Chad');
INSERT INTO country VALUES ('CHILE', 'Chile');
INSERT INTO country VALUES ('CHINA', 'China');
INSERT INTO country VALUES ('CHRISTMAS_ISLAND', 'Christmas Island');
INSERT INTO country VALUES ('COCOS_KEELING_ISLANDS', 'Cocos Keeling Ilands');
INSERT INTO country VALUES ('COLOMBIA', 'Colombia');
INSERT INTO country VALUES ('COMOROS', 'Comoros');
INSERT INTO country VALUES ('CONGO', 'Congo');
INSERT INTO country VALUES ('COOK_ISLANDS', 'Cook Islands');
INSERT INTO country VALUES ('COSTA_RICA', 'Costa Rica');
INSERT INTO country VALUES ('COTE_DIVOIRE', 'Cote D\'Ivoire');
INSERT INTO country VALUES('CROATIA', 'Croatia');
INSERT INTO country VALUES('CUBA', 'Cuba');
INSERT INTO country VALUES('CYPRUS', 'Cyprus');
INSERT INTO country VALUES('CZECH_REPUBLIC', 'Czech Republic');
INSERT INTO country VALUES('DENMARK', 'Denmark');
INSERT INTO country VALUES('DJIBOUTI', 'Djibouti');
INSERT INTO country VALUES('DOMINICA', 'Dominica');
INSERT INTO country VALUES('DOMINICAN_REPUBLIC', 'Dominican Republic');
INSERT INTO country VALUES('EAST_TIMOR', 'East Timor');
INSERT INTO country VALUES('ECUADOR', 'Ecuador');
INSERT INTO country VALUES('EGYPT', 'Egypt');
INSERT INTO country VALUES('EL_SALVADOR', 'El Salvador');
INSERT INTO country VALUES('EQUATORIAL_GUINEA', 'Equatorial Guinea');
INSERT INTO country VALUES('ERITREA', 'Eritera');
INSERT INTO country VALUES('ESTONIA', 'Estonia');
INSERT INTO country VALUES('ETHIOPIA', 'Ethiopia');
INSERT INTO country VALUES('FALKLAND_ISLANDS', 'Falkland Islands');
INSERT INTO country VALUES('FAROE_ISLANDS', 'Faroe Islands');
INSERT INTO country VALUES('FIJI', 'Fiji');
INSERT INTO country VALUES('FINLAND', 'Finland');
INSERT INTO country VALUES('FRANCE', 'France');
INSERT INTO country VALUES('FRANCE_METROPOLITAN', 'France Metropolitan');
INSERT INTO country VALUES('FRENCH_GUIANA', 'French Guiana');
INSERT INTO country VALUES('FRENCH_POLYNESIA', 'French Polynesia');
INSERT INTO country VALUES('FRENCH_SOUTHERN_TERRITORIES', 'French Southern Territories');
INSERT INTO country VALUES('GABON', 'Gabon');
INSERT INTO country VALUES('GAMBIA', 'Gambia');
INSERT INTO country VALUES('GEORGIA', 'Georgia');
INSERT INTO country VALUES('GERMANY', 'Germany');
INSERT INTO country VALUES('GHANA', 'Ghana');
INSERT INTO country VALUES('GIBRALTAR', 'Gibraltar');
INSERT INTO country VALUES('GREECE', 'Greece');
INSERT INTO country VALUES('GREENLAND', 'Greenland');
INSERT INTO country VALUES('GRENADA', 'Grenada');
INSERT INTO country VALUES('GUADELOUPE', 'Guadeloupe');
INSERT INTO country VALUES('GUAM', 'Guam');
INSERT INTO country VALUES('GUATEMALA', 'Guatemala');
INSERT INTO country VALUES('GUINEA', 'Guinea');
INSERT INTO country VALUES('GUINEA_BISSAU', 'Guinea Bissau');
INSERT INTO country VALUES('GUYANA', 'Guyana');
INSERT INTO country VALUES('HAITI', 'Haiti');
INSERT INTO country VALUES('HEARD_AND_MC_DONALD_ISLANDS', 'Heard AND Mc\'Donald Islands');
INSERT INTO country VALUES ('HONDURAS', 'Honduras');
INSERT INTO country VALUES ('HONG_KONG', 'Hong Kong');
INSERT INTO country VALUES ('HUNGARY', 'Hungary');
INSERT INTO country VALUES ('ICELAND', 'Iceland');
INSERT INTO country VALUES ('INDIA', 'India');
INSERT INTO country VALUES ('INDONESIA', 'Indonesia');
INSERT INTO country VALUES ('IRAN_ISLAMIC_REPUBLIC_OF', 'Iran, Islamic Republic of');
INSERT INTO country VALUES ('IRAQ', 'Iraq');
INSERT INTO country VALUES ('IRELAND', 'Ireland');
INSERT INTO country VALUES ('ITALY', 'Italy');
INSERT INTO country VALUES ('JAMAICA', 'Jamaica');
INSERT INTO country VALUES ('JAPAN', 'Japan');
INSERT INTO country VALUES ('JORDAN', 'Jordan');
INSERT INTO country VALUES ('KAZAKHSTAN', 'Kazakhstan');
INSERT INTO country VALUES ('KENYA', 'Kenya');
INSERT INTO country VALUES ('KIRIBATI', 'Kiribati');
INSERT INTO country VALUES ('KOREA_DEMOCRATIC_PEOPLES_REPUBLIC_OF', 'Korea, Democratic People\'s Republic of');
INSERT INTO country VALUES('KOREA_REPUBLIC_OF', 'Korea, Republic of');
INSERT INTO country VALUES('KUWAIT', 'Kuwait');
INSERT INTO country VALUES('KYRGYZSTAN', 'Kyrgyzstan');
INSERT INTO country VALUES('LAO_PEOPLES_DEMOCRATIC_REPUBLIC', 'Lao, People\'s Democratic Republic');
INSERT INTO country VALUES ('LATVIA', 'Latvia');
INSERT INTO country VALUES ('LEBANON', 'Lebanon');
INSERT INTO country VALUES ('LESOTHO', 'Lesotho');
INSERT INTO country VALUES ('LIBERIA', 'Liberia');
INSERT INTO country VALUES ('LIBYAN_ARAB_JAMAHIRIYA', 'Libyan Arab Jamahiriya');
INSERT INTO country VALUES ('LIECHTENSTEIN', 'Liechtenstein');
INSERT INTO country VALUES ('LITHUANIA', 'Lithuania');
INSERT INTO country VALUES ('LUXEMBOURG', 'Luxembourg');
INSERT INTO country VALUES ('MACAU', 'Macau');
INSERT INTO country VALUES ('MACEDONIA_THE_FORMER_YUGOSLAV_REPUBLIC_OF', 'Macedonia, The Former Yugoslav Republic of');
INSERT INTO country VALUES ('MADAGASCAR', 'Madagascar');
INSERT INTO country VALUES ('MALAWI', 'Malawi');
INSERT INTO country VALUES ('MALAYSIA', 'Malaysia');
INSERT INTO country VALUES ('MALDIVES', 'Maldives');
INSERT INTO country VALUES ('MALI', 'Mali');
INSERT INTO country VALUES ('MALTA', 'Malta');
INSERT INTO country VALUES ('MARSHALL_ISLANDS', 'Marshall Islands');
INSERT INTO country VALUES ('MARTINIQUE', 'Martinique');
INSERT INTO country VALUES ('MAURITANIA', 'Mauritania');
INSERT INTO country VALUES ('MAURITIUS', 'Mauritius');
INSERT INTO country VALUES ('MAYOTTE', 'Mayotte');
INSERT INTO country VALUES ('MEXICO', 'Mexico');
INSERT INTO country VALUES ('MICRONESIA_FEDERATED_STATES_OF', 'Micronesia, Federated States of');
INSERT INTO country VALUES ('MOLDOVA_REPUBLIC_OF', 'Moldova, Republic of');
INSERT INTO country VALUES ('MONACO', 'Monaco');
INSERT INTO country VALUES ('MONGOLIA', 'Mongolia');
INSERT INTO country VALUES ('MONTSERRAT', 'Montserrat');
INSERT INTO country VALUES ('MOROCCO', 'Morocco');
INSERT INTO country VALUES ('MOZAMBIQUE', 'Mozambique');
INSERT INTO country VALUES ('MYANMAR', 'Myanmar');
INSERT INTO country VALUES ('NAMIBIA', 'Namibia');
INSERT INTO country VALUES ('NAURU', 'Nauru');
INSERT INTO country VALUES ('NEPAL', 'Nepal');
INSERT INTO country VALUES ('NETHERLANDS', 'Netherlands');
INSERT INTO country VALUES ('NETHERLANDS_ANTILLES', 'Netherlands Antilles');
INSERT INTO country VALUES ('NEW_CALEDONIA', 'New Caledonia');
INSERT INTO country VALUES ('NEW_ZEALAND', 'New Zealand');
INSERT INTO country VALUES ('NICARAGUA', 'Nicaragua');
INSERT INTO country VALUES ('NIGER', 'Niger');
INSERT INTO country VALUES ('NIGERIA', 'Nigeria');
INSERT INTO country VALUES ('NIUE', 'Niue');
INSERT INTO country VALUES ('NORFOLK_ISLAND', 'Norfolk Island');
INSERT INTO country VALUES ('NORTHERN_MARIANA_ISLANDS', 'Northern Mariana Islands');
INSERT INTO country VALUES ('NORWAY', 'Norway');
INSERT INTO country VALUES ('OMAN', 'Oman');
INSERT INTO country VALUES ('PAKISTAN', 'Pakistan');
INSERT INTO country VALUES ('PALAU', 'Palau');
INSERT INTO country VALUES ('PANAMA', 'Panama');
INSERT INTO country VALUES ('PAPUA_NEW_GUINEA', 'Papua New Guinea');
INSERT INTO country VALUES ('PARAGUAY', 'Paraguay');
INSERT INTO country VALUES ('PERU', 'Peru');
INSERT INTO country VALUES ('PHILIPPINES', 'Philippines');
INSERT INTO country VALUES ('PITCAIRN', 'Pitcairn');
INSERT INTO country VALUES ('POLAND', 'Poland');
INSERT INTO country VALUES ('PORTUGAL', 'Portugal');
INSERT INTO country VALUES ('PUERTO_RICO', 'Puerto Rico');
INSERT INTO country VALUES ('QATAR', 'Qatar');
INSERT INTO country VALUES ('REUNION', 'Reunion');
INSERT INTO country VALUES ('ROMANIA', 'Romania');
INSERT INTO country VALUES ('RUSSIAN_FEDERATION', 'Russian Federation');
INSERT INTO country VALUES ('RWANDA', 'Rawanda');
INSERT INTO country VALUES ('SAINT_KITTS_AND_NEVIS', 'Saint Kitts and Nevis');
INSERT INTO country VALUES ('SAINT_LUCIA', 'Saint Lucia');
INSERT INTO country VALUES ('SAINT_VINCENT_AND_THE_GRENADINES', 'Saint Vincent and the Grenadines');
INSERT INTO country VALUES ('SAMOA', 'Samoa');
INSERT INTO country VALUES ('SAN_MARINO', 'San Marino');
INSERT INTO country VALUES ('SAO_TOME_AND_PRINCIPE', 'Sao Tome and Principe');
INSERT INTO country VALUES ('SAUDI_ARABIA', 'Saudi Arabia');
INSERT INTO country VALUES ('SENEGAL', 'Senegal');
INSERT INTO country VALUES ('SEYCHELLES', 'Seychelles');
INSERT INTO country VALUES ('SIERRA_LEONE', 'Sierral Leone');
INSERT INTO country VALUES ('SINGAPORE', 'Singapore');
INSERT INTO country VALUES ('SLOVAKIA', 'Slovakia');
INSERT INTO country VALUES ('SLOVENIA', 'Slovenia');
INSERT INTO country VALUES ('SOLOMON_ISLANDS', 'Solomon Islands');
INSERT INTO country VALUES ('SOMALIA', 'Somalia');
INSERT INTO country VALUES ('SOUTH_AFRICA', 'South Africa');
INSERT INTO country VALUES ('SPAIN', 'Spain');
INSERT INTO country VALUES ('SRI_LANKA', 'Sri Lanka');
INSERT INTO country VALUES ('ST_HELENA', 'St. Helena');
INSERT INTO country VALUES ('ST_PIERRE_AND_MIQUELON', 'St. Pierre and Miquelon');
INSERT INTO country VALUES ('SUDAN', 'Sudan');
INSERT INTO country VALUES ('SURINAME', 'Suriname');
INSERT INTO country VALUES ('SVALBARD_AND_JAN_MAYEN_ISLANDS', 'Svalbard and Jan Mayen Islands');
INSERT INTO country VALUES ('SWAZILAND', 'Swaziland');
INSERT INTO country VALUES ('SWEDEN', 'Sweden');
INSERT INTO country VALUES ('SWITZERLAND', 'Switzerland');
INSERT INTO country VALUES ('SYRIAN_ARAB_REPUBLIC', 'Syrian Arab Republic');
INSERT INTO country VALUES ('TAIWAN_PROVINCE_OF_CHINA', 'Taiwan, Province of China');
INSERT INTO country VALUES ('TAJIKISTAN', 'Tajikistan');
INSERT INTO country VALUES ('TANZANIA_UNITED_REPUBLIC_OF', 'Tanzania, United Republic of');
INSERT INTO country VALUES ('THAILAND', 'Thailand');
INSERT INTO country VALUES ('TOGO', 'Togo');
INSERT INTO country VALUES ('TOKELAU', 'Tokelau');
INSERT INTO country VALUES ('TONGA', 'Tonga');
INSERT INTO country VALUES ('TRINIDAD_AND_TOBAGO', 'Trinidad and Tobago');
INSERT INTO country VALUES ('TUNISIA', 'Tunisia');
INSERT INTO country VALUES ('TURKEY', 'Turkey');
INSERT INTO country VALUES ('TURKMENISTAN', 'Turkmenistan');
INSERT INTO country VALUES ('TURKS_AND_CAICOS_ISLANDS', 'Turks and Caicos Islands');
INSERT INTO country VALUES ('TUVALU', 'Tuvalu');
INSERT INTO country VALUES ('UGANDA', 'Uganda');
INSERT INTO country VALUES ('UKRAINE', 'Ukraine');
INSERT INTO country VALUES ('UNITED_ARAB_EMIRATES', 'United Arab Emirates');
INSERT INTO country VALUES ('UNITED_KINGDOM', 'United Kingdome');
INSERT INTO country VALUES ('UNITED_STATES', 'United States');
INSERT INTO country VALUES ('UNITED_STATES_MINOR_OUTLYING_ISLANDS', 'United States Minor Outlying Islands');
INSERT INTO country VALUES ('URUGUAY', 'Uruguay');
INSERT INTO country VALUES ('UZBEKISTAN', 'Uzbekistan');
INSERT INTO country VALUES ('VANUATU', 'Vanuatu');
INSERT INTO country VALUES ('VATICAN_CITY_STATE', 'Vatican City State');
INSERT INTO country VALUES ('VENEZUELA', 'Venezuela');
INSERT INTO country VALUES ('VIETNAM', 'Vietnam');
INSERT INTO country VALUES ('VIRGIN_ISLANDS_BRITISH', 'Virgin Islands, British');
INSERT INTO country VALUES ('VIRGIN_ISLANDS_US', 'Virgin Islands, U.S.');
INSERT INTO country VALUES ('WALLIS_AND_FUTUNA_ISLANDS', 'Wallis and Futuna Islands');
INSERT INTO country VALUES ('WESTERN_SAHARA', 'Western Sahara');
INSERT INTO country VALUES ('YEMEN', 'Yemen');
INSERT INTO country VALUES ('YUGOSLAVIA', 'Yugoslavia');
INSERT INTO country VALUES ('ZAIRE', 'Zaire');
INSERT INTO country VALUES ('ZAMBIA', 'Zambia');
INSERT INTO country VALUES ('ZIMBABWE', 'Zimbabwe');
