INSERT INTO state VALUES ('ALABAMA', 'Alabama');
INSERT INTO state VALUES ('ALASKA', 'Alaska');
INSERT INTO state VALUES ('ARIZONA', 'Arizona');
INSERT INTO state VALUES ('ARKANSAS', 'Arkansas');
INSERT INTO state VALUES ('CALIFORNIA', 'California');
INSERT INTO state VALUES ('COLORADO', 'Colorado');
INSERT INTO state VALUES ('CONNECTICUT', 'Connecticut');
INSERT INTO state VALUES ('DELAWARE', 'Delaware');
INSERT INTO state VALUES ('DISTRICT_OF_COLUMBIA', 'District of Columbia');
INSERT INTO state VALUES ('FLORIDA', 'Florida');
INSERT INTO state VALUES ('GEORGIA', 'Georgia');
INSERT INTO state VALUES ('HAWAII', 'Hawaii');
INSERT INTO state VALUES ('IDAHO', 'Idaho');
INSERT INTO state VALUES ('ILLINOIS', 'Illinois');
INSERT INTO state VALUES ('INDIANA', 'Indiana');
INSERT INTO state VALUES ('IOWA', 'Iowa');
INSERT INTO state VALUES ('KANSAS', 'Kansas');
INSERT INTO state VALUES ('KENTUCKY', 'Kentucky');
INSERT INTO state VALUES ('LOUISIANA', 'Louisiana');
INSERT INTO state VALUES ('MAINE', 'Maine');
INSERT INTO state VALUES ('MARYLAND', 'Maryland');
INSERT INTO state VALUES ('MASSACHUSETTS', 'Massachusetts');
INSERT INTO state VALUES ('MICHIGAN', 'Michigan');
INSERT INTO state VALUES ('MINNESOTA', 'Minnesota');
INSERT INTO state VALUES ('MISSISSIPPI', 'Mississippi');
INSERT INTO state VALUES ('MISSOURI', 'Missouri');
INSERT INTO state VALUES ('MONTANA', 'Montana');
INSERT INTO state VALUES ('NEBRASKA', 'Nebraska');
INSERT INTO state VALUES ('NEVADA', 'Nevada');
INSERT INTO state VALUES ('NEW_HAMPSHIRE', 'New Hampshire');
INSERT INTO state VALUES ('NEW_JERSEY', 'New Jersey');
INSERT INTO state VALUES ('NEW_MEXICO', 'New Mexico');
INSERT INTO state VALUES ('NEW_YORK', 'New York');
INSERT INTO state VALUES ('NORTH_CAROLINA', 'North Carolina');
INSERT INTO state VALUES ('NORTH_DAKOTA', 'North Dakota');
INSERT INTO state VALUES ('OHIO', 'Ohio');
INSERT INTO state VALUES ('OKLAHOMA', 'Oklahoma');
INSERT INTO state VALUES ('OREGON', 'Oregon');
INSERT INTO state VALUES ('PENNSYLVANIA', 'Pennsylvania');
INSERT INTO state VALUES ('RHODE_ISLAND', 'Rhode Island');
INSERT INTO state VALUES ('SOUTH_CAROLINA', 'South Carolina');
INSERT INTO state VALUES ('SOUTH_DAKOTA', 'South Dakota');
INSERT INTO state VALUES ('TENNESSEE', 'Tennessee');
INSERT INTO state VALUES ('TEXAS', 'Texas');
INSERT INTO state VALUES ('UTAH', 'Utah');
INSERT INTO state VALUES ('VERMONT', 'Vermont');
INSERT INTO state VALUES ('VIRGINIA', 'Virginia');
INSERT INTO state VALUES ('WASHINGTON', 'Washington');
INSERT INTO state VALUES ('WEST_VIRGINIA', 'West Virginia');
INSERT INTO state VALUES ('WISCONSIN', 'Wisconsin');
INSERT INTO state VALUES ('WYOMING', 'Wyoming');
INSERT INTO state VALUES ('PUERTO_RICO', 'Puerto Rico');
